services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: jack
      POSTGRES_PASSWORD: jack
      POSTGRES_DB: jack
    ports:
      - "5432:5432"
    volumes:
      - jack_pgdata:/var/lib/postgresql/data

volumes:
  jack_pgdata:
